# -*- coding: utf-8 -*-
"""assignment9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pbtVCNlLAs56V7l_orw9ZotBLcxcumQ8
"""

# -*- coding: utf-8 -*-
"""Assignment9
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1rAVsfE0ilvTKnilB91FaHLw3yzvMdEQD
"""

# -*- coding: utf-8 -*-
"""Assignment-9
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1LzqicnYNu-6UjykStXdWeBn0LInfyN4o
"""

import numpy as np
import matplotlib.pyplot as plt
 
#Generate line points
def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB
 
#Plotting line -3x+2y = -6
A=np.array([2,0])
B=np.array([0,-3])
AB=line_gen(A,B)
plt.plot(AB[0,:],AB[1,:],label='=-3x+2y=-6')
 
#Shading Required Region
x1=[2,0,0,0]
y1=[0,-3,0,0]
plt.fill(x1,y1,color='blue',alpha=0.3)
 
 
#Labelling points
plt.plot(2,0,'o',color='r')
plt.text(2,0,'A(2,0)')
plt.plot(0,0,'o',color='r')
plt.text(0,0,'O(0,0)')
plt.plot(0,-3,'o',color='r')
plt.text(0,-3,'B(0,-3)')
 
plt.xlabel('x')
plt.ylabel('y')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')
plt.show()